# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a081ad37ec22120ecec3b41f7cf38371bbda09c5523bf14a2e9134731eae328687dc6f475ec9c86f7a662f871d63a19b0f3fcd8f4e26101fc903a7a59d7a77e

test:
  secret_key_base: 25fe331a0aae7f1c853648b2ed356b201ddd93f2ebb029c04d2b20fd06ce3f6f1cea81711db4d7900a8473764a9f4acca11e6bc75bb54df16fcc1b30acfccf5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
